### ISSUE TITLE
채팅방 삭제

### ISSUE THREAD

**Issue by YangHeeDong** [eCommerce-Team-A/GamePT#37]

**Comment by wintersky2** [comment]
@홈페이지
- 신규 강의 나열
- 추천 전문가 나열

@회원가입
- 중복 검증 아이디부분에서 띄우기
- 소환사명, 태그를 입력받아 라이엇 api에 요청하여 실재하는 유저인지 검증한다. 
- 오빈님께서 라이엇 api부분을 맡아주셨다. 
- 프로필사진 첨부 가능

@로그인
- 정보 불일치시 경고문구 출력
- id 찾기는 맞게 입력하면 알림으로 출력 없으면 없다.
- pw 찾기 가입시 입력한 이메일로 임시 비빌번호 발송
- 정보 일치시에 홈페이지로 이동.

@마이페이지 
- 회원의 아이디 닉네임 이메일 출력
- 현재 랭크 출력 승률 그래프와 게임 내 관여수치 표시
- 주문내역 표시
- 정보 수정 가능

@전문가 등록
- 겜피티 서비스는 전문가가 판매자 역할을 수행하기 때문에 권한 승인이 필요하다.
- 관리자는 전문가 승인 페이지를 사용할수 있다.
- 일반 회원은 전문가 등록 페이지를 사용할 수 있다.
- 일반 회원이 승인요청글을 작성하면 관리자가 검토 후 승인 혹은 거부를 할 수 있다.
- 전문가는 마이페이지의 전문가 페이지를 통해 경력과 개인 소개를 등록 및 수정, 삭제 할수있다.

@전문가 강의 관련
- 강의등록이 가능하고 요구되는 내용 입력받음
- 등록이 완료되면 해당 페이지로 이동하고 강의 수정이 가능하다. 
- 본인 강의는 구매 장바구니에 담을수 없고 리뷰작적 역시 불가능 하다.

@구매자 강의 관련
- 상세보기시에 강의소개 커리큘럼 리뷰 담당 전문가 이력을  열람할 수 있다. 리뷰 작성 및 구매 장바구니담기 기능을 할 수 있다.
- 하단에는 해당 전문가의 다른 강의들이 있다.
- 전문가 목록은 전문가 별로 강의 접근을 할 수있는 부분이다. 전문가 클릭시 해당 정보와 강의 목록을 볼 수있다. 상담신청시 1대1 채팅으로 넘어간다.
- 장바구니에 담은 강의들을 선택하여 구매가 가능하다. 포인트 부족시 알림출력, 구매완료시 포인트 차감되고 1대1 채팅으로 이동한다.

@1대1 채팅
- 전문가와 1대1 상담을 할 수있다.

@QnA
- 회원이 관리자에게 문의할 수있는 페이지 이다.
- 회원이 문의를 작성하면 관리자가 답변을 하는 구조이다.

@듀오 게시판
- 등록 시에 나의 라인 및 찾는 라인을 선택, 마이크 사용유무와 메모내용을 입력받는다.
- 생성시 현재 로그인된 유저의 게임 스펙이 라이엇api통해 받은 해당유저의 데이터로 자동 입력되며 글 내용에는 소환사명, 주 포지션, 티어, 찾는 포지션, 승률, 메모, 등록일 정보들이 있다.
- 본인의 글이라면 수정 및 삭제를하게 하는데 수정, 삭제 가능하다.

@로그아웃
- 로그아웃 아이콘을 누르면 로그아웃상태가 되고 홈으로 이동한다.
